### ISSUE TITLE
ソフトウェアIDの編集ができない

### ISSUE THREAD

**Issue by wakata** [DJmegane01/GameCollectWebService#1]
ソフトウェアIDの編集ができない

**Comment by DJmegane01** [comment]
修正予定

**Comment by DJmegane01** [comment]
原因：Controllerクラスのupdate処理でソフトウェアIDを更新対象の処理が書いていなかった。
対応：更新対象として処理を追加(動確済み)
コミットID:918d723795d825bc448834f300331a58aca9f3d5
